# Generated by Django 3.0.7 on 2020-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200614_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_count',
            new_name='answers_count',
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.CharField(default='/img/snegovik.jpg', max_length=120),
        ),
    ]
