# Generated by Django 3.0.7 on 2020-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200616_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.CharField(default='/img/snegovik.jpeg', max_length=120),
        ),
    ]
